# Generated by Django 5.1.7 on 2025-03-11 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Record',
            new_name='Todo',
        ),
    ]
