# Generated by Django 5.1.7 on 2025-03-14 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_rename_record_todo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='details',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
